# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-22 13:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2019, 11, 22, 16, 37, 33, 973348), verbose_name='Опубликовано'),
        ),
    ]
