# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-22 13:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20191122_1637'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-posted'], 'verbose_name': 'статья блога', 'verbose_name_plural': 'статьи блога'},
        ),
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2019, 11, 22, 16, 40, 50, 303363), verbose_name='Опубликовано'),
        ),
    ]
