# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-29 14:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20191122_1640'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='descriprion',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2019, 11, 29, 17, 55, 41, 902587), verbose_name='Опубликовано'),
        ),
    ]
