# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-12-02 18:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20191202_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='video',
            field=models.FileField(default='temp.mp4', upload_to='', verbose_name='Путь к видео'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2019, 12, 2, 21, 34, 0, 38026), verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='data',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2019, 12, 2, 21, 34, 0, 40025), verbose_name='Дата'),
        ),
    ]
