# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-12-02 19:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20191202_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='video_1',
            field=models.FileField(default='temp.mp4', upload_to='', verbose_name='Путь ко 2 видео'),
        ),
        migrations.AddField(
            model_name='blog',
            name='video_2',
            field=models.FileField(default='temp.mp4', upload_to='', verbose_name='Путь к 3 видео'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2019, 12, 2, 22, 28, 30, 764221), verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='data',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2019, 12, 2, 22, 28, 30, 766219), verbose_name='Дата'),
        ),
    ]
