# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-12-02 19:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20191202_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='imagevideo',
            field=models.FileField(default='temp.jpg', upload_to='', verbose_name='Путь к постеру для видео 1'),
        ),
        migrations.AddField(
            model_name='blog',
            name='imagevideo_1',
            field=models.FileField(default='temp.jpg', upload_to='', verbose_name='Путь к постеру для видео 2'),
        ),
        migrations.AddField(
            model_name='blog',
            name='imagevideo_2',
            field=models.FileField(default='temp.jpg', upload_to='', verbose_name='Путь к постеру для видео 3'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2019, 12, 2, 22, 54, 31, 105237), verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='data',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2019, 12, 2, 22, 54, 31, 107234), verbose_name='Дата'),
        ),
    ]
